const generateMDX = ({ options, scale }) =>
  `{/* This file is automatically generated. Do not edit directly */}
import { Meta } from '@storybook/blocks';
import { SpacingScale } from '../../src/components/token-blocks/spacing';

<Meta title="Tokens/${options.title}" />

# ${options.title}
${options.description ?? ""}

<SpacingScale scale={${JSON.stringify(scale)}} />

`;

function formatSpacingTokensAsStory({ dictionary, platform, options, file }) {
  const { allTokens } = dictionary;

  const scale = allTokens.map(({ attributes, value }) => ({
    name: attributes.item,
    value,
  }));

  return generateMDX({ options, scale });
}

module.exports = formatSpacingTokensAsStory;
